<a href="https://colab.research.google.com/github/sswastik630/ML_Algorithms/blob/main/Pytorch/chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [4]:
a=torch.ones(4)    # create a one dimensional tensor of 4 size filled with one.
a

tensor([1., 1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
a[2]=2

In [7]:
int(a[1])

1

In [8]:
a[2]

tensor(2.)

In [9]:
points=torch.zeros(6)

In [11]:
points[1]=4;
points[2]=6;

In [12]:
#We can also pass list in torch
point=torch.tensor([4,5,1,2,3,4,5])

In [13]:
point

tensor([4, 5, 1, 2, 3, 4, 5])

In [14]:
# 2-D tensor
point=torch.tensor([[4,2],[3,6],[1,2]])
point

tensor([[4, 2],
        [3, 6],
        [1, 2]])

In [15]:
point.shape

torch.Size([3, 2])

In [16]:
#Initialize 2-D tensor
a=torch.zeros(4,5)
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [17]:
#Access point in 2D
point[1,1]

tensor(6)

In [18]:
point[1:]

tensor([[3, 6],
        [1, 2]])

In [19]:
#Indexing Range in tensors
point[1:]

tensor([[3, 6],
        [1, 2]])

In [20]:
point[:2]

tensor([[4, 2],
        [3, 6]])

In [26]:
point[:,-1]     #All row from last column

tensor([2, 6, 2])

In [24]:
point[:-1]      #From start till first end

tensor([[4, 2],
        [3, 6]])

In [27]:
#Named tensor

In [29]:
img_t=torch.randn(3,5,5)   # 3D tensor of size 3*5*5

In [30]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [31]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [32]:
#here we are assuming that RGB channel will be third dimension from the end

In [33]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [34]:
# #PyTorch will allow us to multiply things that are the
# same shape, as well as shapes where one operand is of size 1 in a given dimension. It
# also appends leading dimensions of size 1 automatically. This is a feature called broadcasting.
# batch_t of shape (2, 3, 5, 5) is multiplied by unsqueezed_weights of shape (3,
# 1, 1), resulting in a tensor of shape (2, 3, 5, 5), from which we can then sum the third
# dimension from the end (the three channels):


In [35]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)  #Changing the shape of tensor

In [36]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [37]:
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)

In [38]:
img_gray_weighted = img_weights.sum(-3)                   #Mean of color channel
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [39]:
#Tensor factory functions such as tensor and rand
# take a names argument. The names should be a sequence of strings:

In [40]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:934.)
  """Entry point for launching an IPython kernel.


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [41]:
# Similar to indexing, the ellipsis (…)
# allows you to leave out any number of dimensions.

In [42]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [43]:
# The method align_as returns a tensor with missing dimensions
# added and existing ones permuted to the right order:

In [44]:
weights_aligned = weights_named.align_as(img_named)     #Align name of weights_named as img_named
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [45]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [46]:
# If we want to use tensors outside functions that operate on named tensors, we need to
# drop the names by renaming them to None. The following gets us back into the world
# of unnamed dimensions:

In [47]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))