<a href="https://colab.research.google.com/github/sswastik630/ML_Algorithms/blob/main/Pytorch/chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [4]:
a=torch.ones(4)    # create a one dimensional tensor of 4 size filled with one.
a

tensor([1., 1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
a[2]=2

In [7]:
int(a[1])

1

In [8]:
a[2]

tensor(2.)

In [9]:
points=torch.zeros(6)

In [11]:
points[1]=4;
points[2]=6;

In [12]:
#We can also pass list in torch
point=torch.tensor([4,5,1,2,3,4,5])

In [13]:
point

tensor([4, 5, 1, 2, 3, 4, 5])

In [14]:
# 2-D tensor
point=torch.tensor([[4,2],[3,6],[1,2]])
point

tensor([[4, 2],
        [3, 6],
        [1, 2]])

In [15]:
point.shape

torch.Size([3, 2])